# Generated by Django 5.1.5 on 2025-02-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itenerary',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('json', models.TextField()),
            ],
        ),
    ]
