# Generated by Django 5.1.5 on 2025-02-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenerary',
            name='departing_from',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='itenerary',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='itenerary',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
